@host = http://localhost:5220


##                                         Pessoas

### Listar todas as pessoas

GET {{host}}/api/pessoas
Accept: application/json


### Cadastrar uma pessoa adulta

POST {{host}}/api/pessoas
Content-Type: application/json

{
  "nome": "Otávio Vanderlei",
  "idade": 21
}


### Cadastrar uma pessoa menor de idade

POST {{host}}/api/pessoas
Content-Type: application/json

{
  "nome": "Lucas",
  "idade": 16
}


### Buscar pessoa pelo ID

GET {{host}}/api/pessoas/1
Accept: application/json


### Buscar pessoa inexistente

GET {{host}}/api/pessoas/999
Accept: application/json


### Excluir pessoa pelo ID

DELETE {{host}}/api/pessoas/1
Accept: application/json


###                                             Transações


### Listar transações

GET {{host}}/api/transacoes
Accept: application/json


### Cadastrar despesa para pessoa adulta

POST {{host}}/api/transacoes
Content-Type: application/json

{
  "descricao": "Conta de internet",
  "valor": 120.50,
  "tipo": 1,
  "pessoaId": 1
}

### Cadastrar receita para pessoa adulta

POST {{host}}/api/transacoes
Content-Type: application/json

{
  "descricao": "Salário",
  "valor": 2500,
  "tipo": 2,
  "pessoaId": 1
}

### Cadastrar transação para pessoa inexistente

POST {{host}}/api/transacoes
Content-Type: application/json

{
  "descricao": "Teste pessoa inexistente",
  "valor": 100,
  "tipo": 1,
  "pessoaId": 999
}

### Despesa para pessoa menor - deve permitir

POST {{host}}/api/transacoes
Content-Type: application/json

{
  "descricao": "Material escolar",
  "valor": 80,
  "tipo": 1,
  "pessoaId": 2
}

### Receita para pessoa menor - deve bloquear

POST {{host}}/api/transacoes
Content-Type: application/json

{
  "descricao": "Pagamento",
  "valor": 500,
  "tipo": 2,
  "pessoaId": 2
}

###                                                Totais

### Consultar totais por pessoa e total geral

GET {{host}}/api/totais
Accept: application/json

### Excluir pessoa com transações

DELETE {{host}}/api/pessoas/4

### Conferir se a transação também foi removida

GET {{host}}/api/transacoes
Accept: application/json

### Conferir totais após exclusão

GET {{host}}/api/totais
Accept: application/json