@host = http://localhost:5220

# Atualize os identificadores abaixo conforme os registros do seu banco.
@adultoId = 1
@menorId = 2
@transacaoId = 1

###                                       PESSOAS



### Listar todas as pessoas
### Resultado esperado: 200 OK

GET {{host}}/api/pessoas
Accept: application/json


### Cadastrar uma pessoa adulta
### Resultado esperado: 201 Created

POST {{host}}/api/pessoas
Content-Type: application/json

{
  "nome": "Pessoa Adulta",
  "idade": 25
}


### Cadastrar uma pessoa menor
### Resultado esperado: 201 Created

POST {{host}}/api/pessoas
Content-Type: application/json

{
  "nome": "Pessoa Menor",
  "idade": 16
}


### Buscar uma pessoa pelo ID
### Resultado esperado: 200 OK

GET {{host}}/api/pessoas/{{adultoId}}
Accept: application/json


### Buscar uma pessoa inexistente
### Resultado esperado: 404 Not Found

GET {{host}}/api/pessoas/999999
Accept: application/json


### Cadastrar pessoa com nome inválido
### Resultado esperado: 400 Bad Request

POST {{host}}/api/pessoas
Content-Type: application/json

{
  "nome": "A",
  "idade": 25
}


### Cadastrar pessoa com idade inválida
### Resultado esperado: 400 Bad Request

POST {{host}}/api/pessoas
Content-Type: application/json

{
  "nome": "Idade Inválida",
  "idade": 131
}



###                                             TRANSAÇÕES



### Listar todas as transações
### Resultado esperado: 200 OK

GET {{host}}/api/transacoes
Accept: application/json


### Buscar uma transação pelo ID
### Resultado esperado: 200 OK

GET {{host}}/api/transacoes/{{transacaoId}}
Accept: application/json


### Buscar uma transação inexistente
### Resultado esperado: 404 Not Found

GET {{host}}/api/transacoes/999999
Accept: application/json


### Cadastrar despesa para uma pessoa adulta
### Resultado esperado: 201 Created

POST {{host}}/api/transacoes
Content-Type: application/json

{
  "descricao": "Conta de internet",
  "valor": 120.50,
  "tipo": 1,
  "pessoaId": {{adultoId}}
}


### Cadastrar receita para uma pessoa adulta
### Resultado esperado: 201 Created

POST {{host}}/api/transacoes
Content-Type: application/json

{
  "descricao": "Salário",
  "valor": 2500,
  "tipo": 2,
  "pessoaId": {{adultoId}}
}


### Cadastrar despesa para uma pessoa menor
### Resultado esperado: 201 Created

POST {{host}}/api/transacoes
Content-Type: application/json

{
  "descricao": "Material escolar",
  "valor": 80,
  "tipo": 1,
  "pessoaId": {{menorId}}
}


### Cadastrar receita para uma pessoa menor
### Resultado esperado: 400 Bad Request

POST {{host}}/api/transacoes
Content-Type: application/json

{
  "descricao": "Pagamento",
  "valor": 500,
  "tipo": 2,
  "pessoaId": {{menorId}}
}


### Cadastrar transação para pessoa inexistente
### Resultado esperado: 400 Bad Request

POST {{host}}/api/transacoes
Content-Type: application/json

{
  "descricao": "Pessoa inexistente",
  "valor": 100,
  "tipo": 1,
  "pessoaId": 999999
}


### Cadastrar transação com descrição inválida
### Resultado esperado: 400 Bad Request

POST {{host}}/api/transacoes
Content-Type: application/json

{
  "descricao": "A",
  "valor": 100,
  "tipo": 1,
  "pessoaId": {{adultoId}}
}


### Cadastrar transação com valor zero
### Resultado esperado: 400 Bad Request

POST {{host}}/api/transacoes
Content-Type: application/json

{
  "descricao": "Valor inválido",
  "valor": 0,
  "tipo": 1,
  "pessoaId": {{adultoId}}
}


### Cadastrar transação com tipo inválido
### Resultado esperado: 400 Bad Request

POST {{host}}/api/transacoes
Content-Type: application/json

{
  "descricao": "Tipo inválido",
  "valor": 100,
  "tipo": 99,
  "pessoaId": {{adultoId}}
}


###                                             TOTAIS


### Consultar totais por pessoa e total geral
### Resultado esperado: 200 OK

GET {{host}}/api/totais
Accept: application/json


 
###                                             EXCLUSÃO EM CASCATA



### Excluir uma pessoa e suas transações
### Cuidado: atualize o ID antes de executar
### Resultado esperado: 204 No Content

DELETE {{host}}/api/pessoas/{{adultoId}}


### Confirmar que a pessoa foi removida
### Resultado esperado: 404 Not Found

GET {{host}}/api/pessoas/{{adultoId}}
Accept: application/json


### Conferir as transações após a exclusão

GET {{host}}/api/transacoes
Accept: application/json


### Conferir os totais após a exclusão

GET {{host}}/api/totais
Accept: application/json